### ISSUE TITLE
training file missing

### ISSUE THREAD

**Issue by jncj** [qgis/QGIS-Training-Data#8]
https://docs.qgis.org/testing/en/docs/training_manual/introduction/preparation.html
in section 2.2.2 calls for training_data.gpkg
I'm unable to find this file using https://github.com/qgis/QGIS-Training-Data/find/master

**Comment by ghtmtt** [comment]
the Training Manual is in complete restructuring. If you want to use the master version of the training manual be careful: it is in updating and it will be released together with QGIS 3.4 LTR release. So before that no guarantee ;)

But you can use the stable version of the training manual : https://docs.qgis.org/2.18/en/docs/training_manual/

**Comment by DelazJ** [comment]
While i agree that 2.18 is the current full manual to follow, I think that it's good to have people trying the testing doc as the refactoring goes on. Having testers is always nice.
While the 3.4 doc may not be complete yet, I think that available data should correspond to instructions and in this case, the gpkg file should be provided (even not full of all the needed data, at least, the ones the instruction is mentioning), otherwise we'll end up with missing data in the repository. 
Hence, imho this issue should not be closed without the gpkg addition.

**Comment by ghtmtt** [comment]
@jncj  #9 should fix this issue. Please reopen if necessary. As said, in the next months the Training Manual and the data will be "under construction" so, something could not be updated immediately. Thanks!

**Comment by DelazJ** [comment]
Thanks @ghtmtt
